# Generated by Django 2.2.3 on 2021-01-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
