# Generated by Django 2.2.3 on 2021-01-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0004_auto_20210102_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
