# Generated by Django 2.2.3 on 2021-01-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0006_auto_20210102_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='persona',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
