# Generated by Django 2.2.3 on 2021-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0008_comentario_id_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=50),
        ),
    ]
