# Generated by Django 2.2.3 on 2021-01-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0009_auto_20210102_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
    ]
