# Generated by Django 2.2.3 on 2021-01-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0010_auto_20210102_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
    ]
