# Generated by Django 2.2.3 on 2021-01-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(max_length=4)),
            ],
            options={
                'verbose_name': 'promocion',
                'verbose_name_plural': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='promocion')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.Promocion')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
    ]
