# Generated by Django 2.2.3 on 2021-01-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='año',
            field=models.IntegerField(),
        ),
    ]
