# Generated by Django 2.2.3 on 2021-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_auto_20210105_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fondo_promocion'),
        ),
    ]
