# Generated by Django 2.2.3 on 2021-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_promocion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='mensaje',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
