# Generated by Django 2.2.3 on 2021-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0004_auto_20210105_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='mensaje',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
