# Generated by Django 2.2.3 on 2021-01-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20201229_2203'),
        ('promociones', '0005_auto_20210105_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
    ]
