# Generated by Django 2.2.3 on 2021-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0006_estudiante_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='mensaje',
            field=models.CharField(default='{{estudiante.nombre}} era una persona de pocas palabras, le deseamos lo mejor', max_length=200),
        ),
    ]
