# Generated by Django 2.2.3 on 2021-01-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0008_auto_20210105_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='recuerdos')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.Promocion')),
            ],
            options={
                'verbose_name': 'Recuerdo',
                'verbose_name_plural': 'Recuerdos',
            },
        ),
    ]
