# Generated by Django 2.2.3 on 2020-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='horas_semanales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
