# Generated by Django 2.2.3 on 2020-12-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20201221_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.TextField(),
        ),
    ]
